### ISSUE TITLE
Updated game types

### ISSUE THREAD

**Issue by zlehmann** [meraki-analytics/cassiopeia#106]
Apologies if this was addressed already. I know you told me before you have to update cassiopeia in a specific way but I didn't note down what that was. Can you remind me so I can write it down for next time? Sorry very new to coding and working with the api's in general.

There are some game types that don't seem to show up:
Arsr = "Arsr" # Not listed on game constants documentation page
Darkstar = "Darkstar" # Not listed on game constants documentation page

Have they been added to a newer version?

**Comment by jjmaldonis** [comment]
No problem. You probably want to: `pip install --upgrade pip install git+https://github.com/meraki-analytics/cassiopeia.git`  -- I think that should work. Let me know if it doesn't.

If you look in our documentation under `Setup`, usually we have most of what you need there. In this case, it isn't quite there... I should probably update that.

I added Darkerstar from one of our users last week, but ARSR wasn't added. I just added it now but haven't tested it, so hopefully it works. If you want to know if we have something in the future, all that stuff is in the file `cassiopeia/type/core/common.py`. No worries if it's just easier to ask, it only takes a second for me to look since I know where it all is.

**Comment by zlehmann** [comment]
Awesome appreciate it. I'm still learning about git and how to contribute so wasn't sure how to just update that for you guys. Thanks for the help!

**Comment by jjmaldonis** [comment]
git took me years to learn honestly. There aren't even any good intro articles about it that I've ever found. If you want to spend an hour or two learning it, I'd honestly suggest creating two different accounts and use them to push/pull from the same repo (not via collaborators, but rather one user would fork the other user's repo and use pull requests to make changes). That way you learn how contributions work. It's no small task though.

**Comment by zlehmann** [comment]
Thanks that's good advice! I just offered an update to the StatSummaryType list in common.py. It was throwing errors for me without the darkstar and arsr types listed there. Hope I did it right.

**Comment by zlehmann** [comment]
Did that do it?

**Comment by jjmaldonis** [comment]
Yup that worked!

I forgot to close this issue in the commit, so I'm doing it now. The commit is here: 19ddb40e3691c0ab31cc50adff3e10e09d8fc3c5
