### ISSUE TITLE
Auto-Databasing Confusion / Possible Issue

### ISSUE THREAD

**Issue by tylerturk** [meraki-analytics/cassiopeia#107]
I've been trying to figure out exactly how cassiopeia automatically writes to the database and understand it with some calls. When I do a recent games call, however, I'm not seeing anything written to the database. Is this expected? Is there a way I could override this functionality? I'm essentially wanting to build my own backlog of recent games for a couple friends to do more thorough analytics and really like how simple cassiopeia makes this for ranked games. Thanks!

**Comment by jjmaldonis** [comment]
Hmm. So when you use the match endpoint, stuff gets written to the database, but when you use the recent game endpoint, it doesn't? Am I understanding the problem right?

The automatic databasing stuff has been an ongoing issue, and it's something we're putting a lot of time into in the new version. There are a few other `Issues` that might be helpful to read. It seems like the problems people have are often specific to certain databases, so what database are you using?

There is certainly a way to override the functionality, I just don't know what it will be. You may need to modify some files in Cassiopeia. Cass uses SQLAlchemy as an interface layer between Python and your database. SQLAlchemy supports a reasonable number of database types. You can read/skim the SQLAlchemy documentation for more info on that too.

I guess I think we need more specific information in order to be of more help.

Glad you like Cass too!

**Comment by tylerturk** [comment]
That is correct. I'm using MySQL as the database backend. Is there a way to get more verbosity in the database save operations like `"Attempted to save {} to {}".format(data, this_table)`?

I love Cass, it makes life so much easier. There are a few things I may do to extend it like instead of just recent games, pull all games but only from the database but still instantiate the Cass data structures.

**Comment by tylerturk** [comment]
Awesome! TIL about `echo=True` with SQLAlchemy.

**Comment by jjmaldonis** [comment]
Side note:  if there are thing you'd like changed / extended, please let us know here! https://github.com/meraki-analytics/cassiopeia/issues/103
 As we work on the new version, we'd like to incorporate things that our users would like done whenever possible, and this is a good time to do it.

Here are some issues that are related to mysql that might be helpful:  https://github.com/meraki-analytics/cassiopeia/issues?utf8=%E2%9C%93&q=is%3Aissue%20mysql

Cool, glad you figured that out too because I had no idea haha.

**Comment by tylerturk** [comment]
Okay, so I just turned on logging for SQLAlchemy, and here is the gist using Dyrus as an example.

https://gist.github.com/tylerturk/8dfedaaa7ef7e1a94be598a0303b53cb

It's pretty long, but you can see that each summoner is cached. The games, however, are not cached. Does it have something to do with the `HasAll` bits?

**Comment by jjmaldonis** [comment]
Hmmmm I'm really not sure. That could be it. Maybe Riot changed some data and for some reason that's affecting SQLAlchemy. I really don't know...

The DTOs are the objects that get stored in databases, so most of the relevant code should be in the `cassiopeia/type.dto/...py` files. For example: https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/dto/game.py

At the end you'll see a bunch of SQLAlchemy bindings. Maybe something is wrong in there. I know so little about this stuff that I'm unfortunately not much help :/

**Comment by tylerturk** [comment]
It's okay. I appreciate you at least trying to chime in and help here. Is there someone on the project that might be more familiar? I haven't done much with SQLAlchemy, but I can dig if there isn't anyone familiar.

**Comment by jjmaldonis** [comment]
@robrua Is the other developer but he's heads down with some stuff at work for the next week or so so he's pretty busy. He may not know either. The other option would be to see who else has recently been using mysql from the github issues and @ them. Honestly the fastest thing is probably for you to dig into it.

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
