### ISSUE TITLE
XListData data often isn't loaded when it should

### ISSUE THREAD

**Issue by 10se1ucgo** [meraki-analytics/cassiopeia#131]
e.g.:

```python
>>> y = cass.get_champions()
>>> y
[]
>>> random.choice(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Program Files\Python36\lib\random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
>>> len(y)
0
>>> print(y)
{"<class 'cassiopeia.core.staticdata.champion.ChampionListData'>": '[]'}
>>> list(y)
Making call: http://ddragon.leagueoflegends.com/cdn/7.16.1/data/en_US/championFull.json
[<cassiopeia.core.staticdata.champion.Champion object at 0x0000017AC0E2ECF8>, ...]
```

`__repr__`, `__len__`, `__str__`, etc. should probably load the data. IMO, it would be best for the data to be loaded immediately anyways.

**Comment by jjmaldonis** [comment]
Ok, will think on this. In the mean time, you can run `y.__load__()` after `y = cass.get_champions()` to force the pull.

Maybe we can make pulling the data at init an option in the settings for each type in the future. One potential issue with making everything pulled at init by default is that for champions, both the `staticdata/champions` and `champions` endpoints need to be hit, and later the champion.gg api will be as well in order to pull all the contained on a given champion object. Only then would the champion be fully loaded, and it doesn't make a ton of sense for us as developers of a library to choose to load only one or the other of those data.

`__len__` should probably trigger the load, although we went back and forth on `__repr__` and `__str__` multiple times during implementation and ended up deciding that the latter two should probably not trigger a load of all the data, and instead should only print out what data has already been loaded. We aren't super solid on that, but so far it seems to be right path. Happy to hear arguments for/against tho.
