### ISSUE TITLE
Implement Request

### ISSUE THREAD

**Issue by NecroDae** [meraki-analytics/cassiopeia#135]
Would like to see see implementation of summoner.match_history_recent including ranked and nonranked games. Presently Summoner.match_history pulls /lol/match/v3/matchlists/by-account/{accountId} , would like to see implementation of: /lol/match/v3/matchlists/by-account/{accountId}/recent

Thank You
-NecroDae

**Comment by NecroDae** [comment]
If a method for this exists already, I apologize, I'm still learning the library.

**Comment by jjmaldonis** [comment]
Yeah you are right. This isn't available right now but it needs to be. Leaning towards `summoner.recent_match_history` right now, and we'll try to implement it in the next few days.

Thanks for the issue.

**Comment by NecroDae** [comment]
Thank You for the quick feedback, and thank you and the others for making this library. First time working with an API and this Library is making it so much more manageable

**Comment by jjmaldonis** [comment]
With the change to `matchlist` that Riot made recently, recent matches are available through `match_history` now. There is a reasonable chance that Riot depreciates the `matchlist/recent` endpoint at this point. So we're not going to implement this endpoint right now and I'll close this issue as resolved (since this data is accessible). Feel free to reopen it if you feel the need to.
