### ISSUE TITLE
Docs refer incorrectly to request_handling key

### ISSUE THREAD

**Issue by pfmoore** [meraki-analytics/cassiopeia#148]
In http://cassiopeia.readthedocs.io/en/latest/settings.html#request-handling the documentation refers to a key `request_handling` for setting the means of handling unexpected HTTP responses. From what I can tell by checking the code and testing, the actual key name is `handler_configs`.

**Comment by jjmaldonis** [comment]
Thanks, that's a pretty bad doc error. We just chatted about it and decided that `request_error_handling` is probably the most descriptive name, and since we have to change it anyways we'll change it to that.

I'll try to fix this before the end of the weekend.

Also, a couple notes:  1) These only get trigged on errors, and 2) unfortunately they might be a bit buggy. I know the code surrounding these error handlers need to be rewritten because they don't function exactly like the params imply they do, and the implementation needs to be fixed to make them work as expected. And they also could be buggy since I haven't tested them thoroughly.

**Comment by pfmoore** [comment]
Cool - thanks for the quick reply.

Looks like there may well be bugs, as I just had my code fail with a 500 even with exponential backoff set. I'm using this for a crawler, to handle 500 errors. As far as I can tell, every crawler I've ever written has hit intermittent 500's, and some sort of retry strategy is the only way to reliably deal with that. (The sledgehammer retry strategy being to save progress as you go along, make the program restartable, and just restart it every time it fails. But that's obviously useless if you want to run unattended overnight, for example...)

**Comment by jjmaldonis** [comment]
This should be fixed in commit cb24189b22e184453722b0cf1b4b78f12cbbce3c. We haven't updated the code yet, but it's on our todo list still.

>every crawler I've ever written has hit intermittent 500's, and some sort of retry strategy is the only way to reliably deal with that

Yup that's exactly my experience too and it's exactly why we wanted to implement these different handling strategies. I ran my match crawler a couple months ago on two different days for 24 hours each, and it didn't break then (so hopefully most of the code is working). However, if Riot is returning a ton of 500s then eventually the handlers will just throw the error I believe.

I'll close this for now since the main issue is the request handling name (which is fixed), and updating the handling strats is still on our todo list somewhere. Feel free to reopen it though.
