### ISSUE TITLE
Minor "bugs"

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#172]
#Participantstats item list position not respected

#Match.py
```
@lazy_property
    @load_match_on_attributeerror
    def items(self) -> List[Item]:
        ids = [self._data[ParticipantStatsData].item0,
               self._data[ParticipantStatsData].item1,
               self._data[ParticipantStatsData].item2,
               self._data[ParticipantStatsData].item3,
               self._data[ParticipantStatsData].item4,
               self._data[ParticipantStatsData].item5,
               self._data[ParticipantStatsData].item6
        ]
        version = _choose_staticdata_version(self.__match)
        return SearchableList([Item(id=id, version=version, region=self.__match.region) for id in ids if id])
```
Currently the list will only contain items that exist. It would be useful to have the position of each item preserved as well (eg. to see a relationship between active items and key binds). 

I can think of 2 ways of solving this:
1. Add properties for item0-6 to the stats object
2. Add empty items to the list to let it contain everything (or at least an option to with a param).

**Comment by jjmaldonis** [comment]
Hey so is this something that is affecting your directly or something that you noticed could be improved?

**Comment by tyuo9980** [comment]
This is something that could be improved. The issue is that there is a loss of information and I feel that it's something that should not happen.

**Comment by jjmaldonis** [comment]
Ok so in that case I'm going to ask you to update this post (preferably by editing your main post) with new minor bugs you find.

This is for two reasons: first, having many small bugs on the issue tracker pollutes the space and makes game-breaking issues less visible for other people searching for problems they are having. Second, every time someone makes an issue it requires us to think: "What is broken? Is this bug a real bug, a mistake by the submitter, or something we are temporarily okay with? What should the correct user experience be? How can this be fixed? Will those fixes impact other pieces of functionality in Cass? How much work is required to implement the correct fix; and related, how important is this fix related to all the other things we have to do, both in Cass and in real life? Finally, how should we respond to the submitter?" Just answering those questions, even before we do any actual work, is non-trivial and takes some time (and you'd be amazed how much time this project consumes, even without us using it for our own projects).

I'd bet there are between 100 and 300 of these bugs in Cass if you really go looking, and you've found a few of them so far. However, since we do this in our spare time, we don't have the time to fix (and figure out how to fix) them all right now (although we hope we can someday). So part of our job is to prioritize the things that affect the functionality that people (especially us!) want to use, and weigh that along with what sounds like fun to do (so we don't get too burned out). For example, testing the new SQLAlchemy store, documenting it, and getting other databases (e.g. Mongo and Reddis) available to users are a few not-super-fun things that imo are very important to do.

These bugs are less important, but together many minor improvements can provide a very significant user improvement. To that end, I've renamed this issue "minor bugs" and I ask that you edit your post in the future with additional small improvements you (and others) identify. We'll check back on this thread regularly when we have some time and energy to see what's new and what can be improved. As the bugs pile up, we'll occasionally make a run through and try to check some of them off the list.

If you find bugs that are significantly impacting your ability to use Cass productively, please create a new issue so that we can prioritize it independently.

I hope that makes sense.

P.S. to anyone else reading this: We really appreciate your help answering questions and issues, it's a big deal, so thank you.

**Comment by Xpheriono** [comment]
I might be mistaken here. Pretty new to Python so please feel free to let me know if I'm being dumb.

This code

```
for entry in leagues.flex:
            if entry.summoner.name == playerName:
                print(entry.summoner.name, leagues.fives.tier, entry.division)
```

gives the same results as this code

```
for entry in leagues.flex:
            if entry.summoner.name == playerName:
                print(entry.summoner.name, leagues.fives.tier, entry.division)
```

Both sets of code will return 5v5 Flex, am I missing something or is there no way to get solo/duo ranks?

**Comment by jjmaldonis** [comment]
Ouch, good catch. That was a typo on our end. It's fixed now, and you can update Cass from GitHub using:  `pip install git+https://github.com/meraki-analytics/cassiopeia.git`

**Comment by Xpheriono** [comment]
Thanks for the quick fix, that was really awesome of you!

I've run into one more problem though while trying to install the SQLAlchemy plugin with pip.

I get the following error message:
```
Could not find a version that satisfies the requirement cassiopeia-sqlalchemy (from versions: )
No matching distribution found for cassiopeia-sqlalchemy
```

Is the plugin still supported?

**Comment by jjmaldonis** [comment]
@Xpheriono I haven't heard of that problem before. @Satrium is working on the SQLAlchemy plugin. He's cleaning up the code now and then will submit a big PR to fix some things. If you can wait until that's merged then I'm guessing this will be fixed at the same time. However, after googling your error it's possible that this is an issue with your environment. Try looking through the results [here](https://www.google.com/search?q=pip+Could+not+find+a+version+that+satisfies+the+requirement+(from+versions%3A+)+No+matching+distribution+found+for&oq=pip+Could+not+find+a+version+that+satisfies+the+requirement+(from+versions%3A+)+No+matching+distribution+found+for+&aqs=chrome..69i57.10575j0j1&sourceid=chrome&ie=UTF-8) (I found some relevant discussions in other github issues).

By the way, feel free to post breaking changes as main issues rather than in this post. I should probably change the title to clarify that.

**Comment by jjmaldonis** [comment]
@tyuo9980 Actually I think I am going to close this issue.

Regarding the items issue you discussed above, after thinking about it for a while, we decided we are going to leave the code as-is. Including `None` for empty slots just requires the user to make another check to see if the item is `None`, which is, for 95+% of use cases, just an unnecessary hassle. It will require code like this: `items = [item for item in items if item is not None]` as a precursor to doing almost anything with items, and that's just a pain.  This is one of the rare cases were we are okay sacrificing "perfect" data, in part because it improves the user experience so much for essentially everybody (including you since you said you don't actually use the empty slots for anything). Technically, the empty item slots can still be identified using the underlying data that is accessible via the `.to_dict()` method, so if worst comes to worst, someone can just use that.

@Xpheriono If you want to keep talking about the SQL problem, please open another issue and reference this one within it. It will help me keep track of what's going on.

**Comment by Satrium** [comment]
@Xpheriono the sqlalchemy store is no longer named cassiopeia-sqlalchemy but cassiopeia-sqlstore

You might want to wait til @jjmaldonis makes a new release, because meraki-analytics/cassiopeia-datastores#4 was merged a few hours ago.

**Comment by jjmaldonis** [comment]
@Xpheriono @Satrium Okay, a new release was made. You should be able to install via `pip install cassiopeia-sqlstore`.
