### ISSUE TITLE
[Enhancement] option to nonlazily load

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#188]

**Comment by jjmaldonis** [comment]
We've been thinking about this and have an implementation in place, but it hasn't been tested much. However, we haven't identified a clear use-case where not lazy loading improves something, so we haven't put much emphasis on this. Do you have a use case where you prefer non-lazy loading?

**Comment by tyuo9980** [comment]
One problem with lazy loading is that you dont know exactly when a call to riot api will happen and it would be useful to control it. For example, i can achieve better load balancing and scaling with my app if i could batch objects(eg. list of matches ).

Also for containers of cassiopeia objects, properties for the container will be incorrect until data is populated. For example if I want to know how many matches have been returned by match_history, the array will be empty until i access an element to trigger the api call. 

Side issue: to_json() should make an api call if data has not been already populated. I have to access a variable and leave it unused just for the purpose of loading data.

**Comment by jjmaldonis** [comment]
One thing we have been considering is adding a public `.load()` method, which will allow you to write code like `annie = Champion(name='Annie').load()` or `matches = [m.load() for m in match_history]` to force an object to load. This would allow you to have very fine grained control over when data is loaded, at the expense of having to type more code. Would this solve your load balancing issue?

We will consider having `to_json()` load the data. So far, it's been very nice having `to_dict` _not_ load the data, and only showing information that is currently available. Maybe `to_json` and `to_dict` can work slightly differently, although that was never the plan. Even without having `to_json` load the data, running `annie.load().to_json()` doesn't sound like a terrible API. We will make sure `.load()` doesn't throw an error if it has already been loaded.

Side comment about using `to_json`: We never really intended `to_json` to be used to send all the data that comes from the API to your frontend. Instead, we always assumed that devs would pick out the information they wanted from an object, put that data into a dict/json, and then send only that information to their frontend. By sending the entirety of `to_json()` to the frontend, a malicious person could essentially use your website as an additional source of data, and thereby use your production API key for themselves. In addition, by constructing the dict from the data on the object, the dev can add additional information that they compute to that dict/json before sending it to the frontend.  Final comment on this, Cass is more targeted towards apps that want to manipulate data rather than just "passing through" that data from Riot to the frontend. Cass provides an interface for working with data that is meant to be extremely convenient, and that's a bit part of our goal. Although we also provide a bunch of utility stuff (like caching and databasing) that "pass through" applications will certainly benefit from.

>Also for containers of cassiopeia objects, properties for the container will be incorrect until data is populated.

So this should never be the case -- if it is, let us know and we'll almost certainly fix it. For example, calling `len` on a match history will load the entire match history before returning the length. To the user, the containers that Cass uses should act exactly as you would expect, with the exception that they only load data if/when you need it. That's why calling `len` pulls all the data.

We've been doing lazy and/or eager loading with Cass for a long time, so you'll have to trust us that we know what we're doing. The "old" Cass (and Ori) differentiated between lazy and eager loading, and we used that system for a few years. There were a few inconveniences that sprang up that we didn't particularly like, so when we started in on this version of Cass/Ori we were very careful about how we wanted to load data, and we are very happy with the results. Once we figured out the right way to handle all the different pieces, they came together very nicely, including the loading functionality.

What is very helpful is if you tell us what your use cases are and why what Cass provides is hindering those use cases (e.g. the load balancing). We've put a ridiculous amount of time and effort into thinking about functionality that we ourselves will probably never use, in order to provide a product that anyone can use for (nearly) any use case. So far, we haven't had to make too many sacrifices in order to accommodate every use case we can think of, so we're pretty confident that minor changes in functionality can enable use cases that we haven't thought of yet (while continuing to accommodate all the other use cases out there). You'll notice how many options/configuration switches there are in the documentation -- that's a sign of what we have already considered since Cass was released a few months ago.

**Comment by tyuo9980** [comment]
.load() would sound perfect for my use case, which would be to load a collection of objects whenever convenient and pass them along for aggregation or other purposes at a later time. 

len(history) does work correctly, sorry for the mistake

**Comment by jjmaldonis** [comment]
Ok, added a new `.load()` method. You should be good to go now.
