### ISSUE TITLE
Roles not assigned properly

### ISSUE THREAD

**Issue by InvalidPointer** [meraki-analytics/cassiopeia#194]
Got participant .side, .role, .lane:

> Side.red Role.support Lane.bot_lane
> Side.blue Role.support Lane.bot_lane
> Side.blue SOLO Lane.top_lane
> Side.blue None Lane.jungle
> Side.blue Role.adc Lane.bot_lane
> Side.blue SOLO Lane.mid_lane
> Side.red None Lane.jungle
> Side.red SOLO Lane.mid_lane
> Side.red Role.adc Lane.bot_lane
> Side.red SOLO Lane.top_lane

Why roles can't be assigned for middle, jungle and top players according to their lanes automatically (Role.middle, Role.jungle and so on already exist)?

**Comment by jjmaldonis** [comment]
This isn't a Cass problem, this data is what the Riot API returns. We have a plugin for Cass that will do a much better lane assignment here: https://github.com/meraki-analytics/role-identification

Riot's algorithm for determining roles/lane is based on in-game data such as positions during the first 10 minutes. If the algorithm can't figure it out, it results in weird values. The lane information from champion select is for some reason not passed through to the API, but even if it were, it wouldn't be especially helpful due to things like swapping in champ select. If you want good data, I encourage you to use the plugin above. You'll need a champion.gg API key. Our algorithm works very well, and it works for current games as well as already-played matches.

**Comment by InvalidPointer** [comment]
Thanks for quick and awesome replies, they are very helpful!
