### ISSUE TITLE
league promo series does not exist

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#207]
I would like to get the promo series status of a player for a ranked queue.

Theres the "promos" attribute but its a nonetype for those in a promo

get_league_positions(...)[0].promos

**Comment by jjmaldonis** [comment]
Promo series works correctly. You need to carefully check the data before making an issue like this. You also need to provide *specific* examples for all your issues, with code to exactly and explicitly reproduce the problem. This also acts as a check to make sure you aren't doing something wrong, because you are forced to think about the problem and reproduce it using the minimal amount of code.

If you have a specific example of this not working let us know. But seriously, next time just give us a concrete example so we can check it rather than using `...` in your post.

**Comment by tyuo9980** [comment]
Its difficult to provide specific examples for issues like this because i dont own an account that i can keep in a promo series. As a result i checked streams and riot api to find an account that was in a promo series. From those accounts i gathered the promos attribute was of nonetype. Im sure at this moment those accounts are no longer in promos and it would not be possible for you to double check those specific accounts.

If i do come across this again i will open another issue, but im not sure how much more useful information i can provide since there is no error thrown.
