### ISSUE TITLE
Allow endpoints that require summoner info to be passed in directly

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#217]
s = cass.get_summoner() is required before calling certain endpoints that require the summoner object to be passed in such as cass.get_match_history(summoner=s). This results in an additional sequential call to riot api and significantly reduces throughput. 

For example, I have a database of summoner/account ids and would like to call get_match_history() for each of them, but I'd have to call get_summoner() first. 

Allowing something like cass.get_match_history(summoner_id=123, region=123) would significantly speed up tasks.

These cass objects currently do allow you to pass either a cass.Summoner, str, or int obj but the initialization asserts for cass.Summoner.

**Comment by jjmaldonis** [comment]
Just use `cass.get_match_history(summoner=Summoner(id=123, region="NA"))`. I.e. create the summoner object with the data you want, then pass it in to whatever method you want.

I've updated the type annotations to only accept Summoner objects rather than ids or strings.

**Comment by tyuo9980** [comment]
Thats the exact scenario I would like to avoid because its an additional call and increases RTT by 0.3-0.5s per call

**Comment by tyuo9980** [comment]
I cant cache because it memory leaks, and I also have a lot of background workers so caches wont be shared among them

**Comment by jjmaldonis** [comment]
`s = Summoner(id=123, region="NA")` does not make a call. A call is only made when data that is unavailable is requested. So if you run `s.account.id` it's going to make a call because `s`'s account id is unavailable. However, `s.id` _will not_ make a call because the `id` _is_ available.

Just pass in the account information when you create the summoner (and don't call `.load()` on it), then pass the summoner to the match history method. (The match history method needs the summoner's account id, not it's id.)
