### ISSUE TITLE
Slow attribute accessors

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#220]
```
        global_items_data = {}
        for participant in match.participants:
            participant_items = {item.id for item in participant.stats.items[0:6] if item}
            for item in participant_items:
                if not participant.champion.id in global_items_data:
                    global_items_data[participant.champion.id] = {}
                if item in global_items_data[participant.champion.id]:
                    global_items_data[participant.champion.id][item] += 1
                else:
                    global_items_data[participant.champion.id][item] = 1
```
This piece of code generates the frequency of items bought by each participant. Max is 10 dicts created, each having 6 entries. 

Timing this on my local machine reveals that it takes 18ms to run, which is absurdly slow. Something around this scale should be an order of magnitude faster. Aggregating 100 matches for only this piece of code takes 1.8s and is currently the bottleneck in my project.

Is there a faster alternative to grabbing data from the cass objects?

**Comment by jjmaldonis** [comment]
What part of this is slow?

**Comment by tyuo9980** [comment]
Its just slow in general. I benchmarked dict creations; the same number of entries and dicts as the code above and python isnt slow at it, so it must have something to do with how cass handles its objects.

**Comment by jjmaldonis** [comment]
Alright well if you can narrow it down to what explicitly is being slow in Cass then I will look into it at least briefly.

**Comment by tyuo9980** [comment]
I have an aggregation of 25 matches running sequentiakly. It takes 1.3s for it to compeltely run. These aggregations are simple increments and if conditions, occasionally inserting key val pairs to dicts. Python def isnt the issue

**Comment by jjmaldonis** [comment]
I'm not sure if that was meant as a reply to my comment or not, but what I meant was: I believe you that there is something in Cass that is slow. However we might be just fine with that, Cass isn't meant to be super fast.

If you want me to take some time to figure out what your issue is, I'd like you to put some more effort into figuring out where the problem lies. At this point, we've put in a non-trivial amount of time helping you personally and fixing all the bugs you find very quickly, and by now you should have a fairly decent understanding about how Cass works. As a result, I now expect you to put some effort into figuring out _where_ the issues are, not just what they are. I tried to hint at this a little less bluntly in your last PyCurl issue, but I figured I'd say it explicitly here.

If you'd like you can take this as a learning experience, and you'll probably learn a lot regardless. Take some time to narrow down what specifically is being slow until you can't dig any deeper and are really at a loss for what's going on. At that point, if you explain what you've learned and where you think the problem lies (and what your evidence for that is), I'd be happy to look into this in more depth.

**Comment by tyuo9980** [comment]
I really appreciate all the help and the speedy responses to the issues I posted. I usually post issues when there's a problem and update it with more information as I dig in deeper and find out more, just so maybe someone with more context might have also run into this can add on with what they know. I understand that this might make it seem like the problem is too vague and I'll try to not post as hastily next time.

Related to this issue: The match.participant accessors generate a list of participants every time its referenced. And every iteration of the for loop also accesses the attribute, causing the participants array to be generated multiple times. Maybe cass can be a bit more clear on this since people usually might not expect that accessing an attribute will do something under the hood
