### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by hingston** [meraki-analytics/cassiopeia#260]

**Comment by jjmaldonis** [comment]
We'll probably do this in conjunction with the v4 updates to the API. Python changed some of their core code and broke some functionality in Cass, and we'll need to reevaluate how to update it.

**Comment by hingston** [comment]
@jjmaldonis is there any ETA on this and could I help in anyway? I'd really like to use Cassiopeia with [Google Cloud Functions](https://cloud.google.com/functions/docs/concepts/python-runtime) and it only supports Python 3.7.1

**Comment by jjmaldonis** [comment]
Riot took down the v4 endpoints due to some issues and hasn't put them back up yet. After they are back up, it could easily take a couple weeks to get Cass updated because the changes are non-trivial and we have to do things like this as well.

If you want to help us update Cass to 3.7 that'd be great. Right now I don't even know/remember what the issues are. I'm pretty sure there's an issue with PIL and 3.7, and iirc there's also an issue with the `typing` module somewhere. If you can document the issues and let us know what they are that would be huge. Even line numbers + error messages are helpful, and if you can diagnose what the issue is at a higher level that's great too. I think you'll run into the PIL issue first, so after documenting that you might just be able to remove the PIL imports to "get rid of" that error, and then the next error should pop up. If you know how to fix the issues that come up that's awesome, but if not we might have some ideas if you let us know what the errors are.

**Comment by jjmaldonis** [comment]
Cass now support 3.7

**Comment by hingston** [comment]
@jjmaldonis Is there an ETA on the next release? Today v3 API is shutdown.
