### ISSUE TITLE
Incorrect Match history uri 

### ISSUE THREAD

**Issue by abhargv3** [meraki-analytics/cassiopeia#263]
I am trying to get the match history from the match_history_uri component from a summoner object. But sometimes it gives me an incorrect url
For example if I try my friend's summoner name "Redvibez" the url given to me is `/v1/stats/player_history/NA1/32601003` but its supposed to be `/v1/stats/player_history/NA/32601003`

For reference here is the snippet from the python shell to get the match history

```
summoner = cass.get_summoner(name="Redvibez", region="NA")
summoner.match_history_uri
Making call: https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/Redvibez
'/v1/stats/player_history/NA1/32601003'
```

**Comment by jjmaldonis** [comment]
Great, thanks for making an issue. This problem happens because a while back Riot used `NA` rather than `NA1` to refer to the region for North America, and then later switched to using `NA1`. All the API endpoints use `NA1`, so we use that in Cass internally. But clearly you've found that Riot still uses `NA` for the match history URIs for the players who created accounts before Riot made the switch to `NA1`.

When the API team re-releases the `v4` endpoints, I was planning to do a big overhaul of everything that needs to be done, so my plan right now is to fix this issue at the same time. That probably won't happen for another couple weeks because I'm pretty busy in the near future.

For a temporary workaround, you should be able to test to see if the URI that Cass gives works, and if it doesn't just replace `NA1` with `NA`. I know that's not ideal, so we'll fix it sometime soon I hope.
