### ISSUE TITLE
How does this compare to RiotWatcher?

### ISSUE THREAD

**Issue by GiacomoLaw** [meraki-analytics/cassiopeia#277]
Hi all,

I use [RiotWatcher](https://github.com/pseudonym117/Riot-Watcher) in some of my Python applications to link to Riot Dev api. How does this compare?

Do they achieve different things?

Thanks!

**Comment by jjmaldonis** [comment]
RiotWatcher is an excellent library that provides you with the basics for using the Riot API. It's good for people who want to learn how the Riot API works or who want to custom-build every aspect of their application. RiotWatcher provides you with functions to get dictionary objects from the Riot API and also rate limits your API key so you don't get blacklisted.

Cass is meant to be much more feature-full than RiotWatcher. In addition to rate limiting, Cass provides a nice interface for working with the data from the Riot API. We have so many quality of life features that it's hard to list them all, but the popular ones are: the ability to interface with the champion.gg API within Cass, easy access for your own summoner in a match, replacement of `matchref` by `match` so you don't need to worry about the differences between them, perfect optimized rate limiting that prevents you from making unnecessary requests, information about patches (like when they were released), a cache, integration with databases, ... and many more... Our docs contain information about most of this stuff, and we are working on rewriting them to better illustrate what Cass can do and how you can do it.

Basically, we needed all the stuff in Cass for our own work, so we decided to make it for everyone so they don't all have to remake the same stuff. There are some very nice features of Cass that don't exist in any other Riot API library except for Orianna (java), which we also write.

Cass is also much more complicated than RiotWatcher. There's a lot going on under the hood, so depending on your level of experience it can be confusing. We took a high-level approach to the design, which means that the interface looks like e.g. `annie = Champion(name="Annie")` rather than searching through the list `watcher.static_data.champions()`. Cass feels different, and you have to think about how you use it differently and at a higher level than using the Riot API. It's more complex, but more powerful.

The other library worth mentioning is Pantheon. Pantheon provides async access to the Riot API and functions similarly to RiotWatcher.

A brief rundown is:

* RiotWatcher provides easy access to the Riot API and allows you to build everything yourself.

* Pantheon is like RiotWatcher but designed for async requests.

* Cass is much more powerful and feature-rich than RiotWatcher, and is best for when you just want to build your application and not have to worry about how anything works under the hood.

**Comment by GiacomoLaw** [comment]
Awesome, thank you so much!

**Comment by jjmaldonis** [comment]
chat.openai.com has this to say about it:

```
It's difficult to say which library is "better" because the right choice of library depends on your specific needs and preferences. Both the `cassiopeia` and `riotwatcher` libraries provide access to the Riot Games API, which allows developers to retrieve data about matches, players, and other aspects of League of Legends. However, each library has its own unique features and capabilities.

For example, the `cassiopeia` library is a higher-level library that provides a more user-friendly interface for accessing the Riot Games API. It allows developers to access data about matches, players, and other game elements in an object-oriented way, which makes it easier to work with and understand. It also includes support for caching and rate limiting, which can help improve performance and avoid reaching the API's rate limits.

On the other hand, the `riotwatcher` library is a lower-level library that provides a more direct interface to the Riot Games API. It allows developers to access the raw data returned by the API, which gives them more control over the data they retrieve. However, this also means that developers will need to write more code to process and work with the data. The `riotwatcher` library does not include support for caching or rate limiting, so developers will need to implement these features themselves if needed.

In general, the `cassiopeia` library may be a better choice for developers who want an easier and more user-friendly way to access the Riot Games API, while the `riotwatcher` library may be a better choice for developers who want more control over the data they retrieve from the API. Ultimately, the right choice of library will depend on your specific needs and preferences. You may want to try both libraries and see which one works best for your project.
```

Just incredible.
