### ISSUE TITLE
statPerk data is only found in match participant data when using to_dict or to_json

### ISSUE THREAD

**Issue by ereesman** [meraki-analytics/cassiopeia#297]
I would expect that statPerk0, statPerk1, and statPerk2 would be available as members of match.participant.stats. I'd also expect that there is support for statPerk ddragon info such as name + effect for each statPerk. I didn't see any issues open or closed addressing this. Is this on the to-do list somewhere?

**Comment by jjmaldonis** [comment]
I don't think there is any ddragon info with the name and effect for each statPerk. If you find it you can post it here.

You can access the statPerk values in Cass by looking at the participant's `.runes` dictionary.

**Comment by ereesman** [comment]
I believe this is actually incorrect: 

> You can access the statPerk values in Cass by looking at the participant's .runes dictionary.

The only way statPerk info is accessible is via the to_json/to_dict methods on the ParticipantStats object. The runes dictionary only ever contains 6 items, which relate directly to primary/secondary runes (excluding the 3 statPerk options).

You can see the following:

`>>> len(match.participants[0].runes)
6`

You can find the dragon info for these [here](https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/perks.json) although not officially a ddragon resource this was linked on the Dev Communities discord.

**Comment by jjmaldonis** [comment]
Yeah we don't support CDragon as a way to get data. I was one of the original creators of the project and am on the management team, although I've pretty much dropped off the face of the earth for that project. Everyone else is doing a great job keeping it up to date and providing super useful data.

It would be really nice to support CDragon in Cass, but I'm still not sure how reliable the data formats are. We could get breaking changes to that data format without notice at any time, which would in turn cause breaking changes to people's project and they would feel like those breaking changes came totally out of the blue. DDragon and the Riot API, on the other hand, are either well-versioned or very consistent, so it's much easier to predict when changes will occur (and therefore keep on top of them) so that Cass's data gathering mechanisms don't break people's programs. Introducing CDragon as a data source means that we have to react to changes immediately or risk Cass just plain being unusable for _everyone_. Right now we aren't willing to make that type of a "drop everything" commitment when the library already does nearly everything without CDragon :) It's not out of the question to provide a plugin that uses CDragon as a data source and monkey-patches Cass's interface/data. If you're interested in doing that, you could look at the (now obsolete) champion.gg plugin and talk to us more.

>The only way statPerk info is

I'm actually not entirely sure what you mean by statPerk info, but I'm guessing it's the `perk*Var*` values return by the API. Looking [here](https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/core/match.py#L150) and [here](https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/core/match.py#L1315), it seems like the `perk*Var*` data is available as the values in the `Participant.runes` dictionary.

Update: Oh, I'm guessing you mean the three Offense/Defense/Flex runes that are in addition to the 6 normal runes you select. Does the Riot API return that data? I'm not seeing it in their docs anywhere.

**Comment by jjmaldonis** [comment]
Another option would be to simply hard-code the stat perk data into Cass (or maybe read it from a json file like we do for patches). As long as we have good error handling if Riot adds a new stat rune ID to prevent Cass from breaking immediately, that seems like a reasonable solution.

**Comment by ereesman** [comment]
Yes you've got it, it's the 3 minor "statPerk" runes that complete a rune loadout in Runes Reforged. Without this info your rune info is incomplete. These fields exist in the response payload from Riot API, however, they are indeed not documented even in the official docs. There is an open issue in the riot repo for this.

**Comment by jjmaldonis** [comment]
RIP alright. If you want to hardcode the data at the top of `core/match.py` for now, and submit a PR to add this data to the `particpant.runes` dictionary, I'd be happy to merge it. Otherwise I'll plan to take care of it when Riot releases the TFT endpoints because I have a backlog of things to do when that comes out anyways.

**Comment by ereesman** [comment]
I'd be happy to submit a PR for that.
