### ISSUE TITLE
Getting error looking for league data

### ISSUE THREAD

**Issue by Tap84** [meraki-analytics/cassiopeia#307]
`('League' object has no attribute '_lazy__entries')`
This error occurs when accessing this data `summoner.league_entries.fives.league.entries`. From what I can see and what people say, this is an error with an outdated version of cass, and it only happens when I am working on my laptop. However I have uninstalled and reinstalled cass many times using the github link as the source for pip, as well as running the program in a pipenv installing from these packages 
```
[packages]
django = "*"
coverage = "*"
requests = "*"
roleml = "*"
cassiopeia = {git = "https://github.com/meraki-analytics/cassiopeia"}
```
I'm not sure what I can do to fix this error, I have reinstalled python and removed all my pip packages then reinstalled them, and I'm still getting this error.

Pip freeze shows that I am using cassiopeia version 4.0.6, which from what I can tell is the most recent version

**Comment by jjmaldonis** [comment]
@Tap84 This was indeed a bug, I have no idea how it got in there because I'm almost positive I tested this exact functionality a few weeks ago when fixing a similar bug. Thanks for figuring out how to reproduce this. You should be able to pull from github or pypi and get the latest version with the bugfix.
