### ISSUE TITLE
Accessing tournament match data

### ISSUE THREAD

**Issue by seanbow** [meraki-analytics/cassiopeia#315]
Normal online matches are specified by just a region and game ID which is easy to translate into the Cassiopeia API. For a tournament game however things are different; how would I fetch the data from the following match using Cassiopeia?

https://matchhistory.na.leagueoflegends.com/en/#match-details/ESPORTSTMNT01/1311996?gameHash=c1ed3b5ee8e5812f&tab=overview

**Comment by jjmaldonis** [comment]
Hey, just catching up on this now. Unfortunately Cass doesn't support tournament games right now. You could add a datasource that does provide them, but that would be a decent chunk of work. We've decided that, at least for the time being, Cass won't support tournament functionality because it's a whole different ballgame from the typical API experience. We also don't use it, so that makes it very hard for us to test it and make sure the functionality is always working for our users.

**Comment by seanbow** [comment]
Ah gotcha, thanks for the info
