### ISSUE TITLE
Is there a way to set the default region?

### ISSUE THREAD

**Issue by realdevvora** [meraki-analytics/cassiopeia#396]
The `cass.set_default_region()` function doesn't work anymore, and neither does the `"default_region"` in the settings. Is there a way to automatically set the default region, or do I have to do it manually now? Thank you.

**Comment by jjmaldonis** [comment]
Hey, no there is not. We need to remove that functionality. You'll have to specify the region in the objects you create, but once you do that for one object then any object you create from that will inherit the region. E.g. `me = Summoner(name=..., region="NA")` followed by `me.match_history` allows you to create a match history object without specifying a region because it inherits from the summoner.

**Comment by realdevvora** [comment]
Oh alright, makes sense. Thanks for telling me.
