### ISSUE TITLE
none of the properties of cassiopeia.core.match.Team are available

### ISSUE THREAD

**Issue by timplaw** [meraki-analytics/cassiopeia#407]
I can't access any of the properties.

new_match = Match(id=new_match_id, region=region)
                print(new_match.red_team.win)
                input()
                for participant in new_match.participants:
                    print(
                        participant.team.baron_kills,

red_team fails and so does participant.team

**Comment by retzugil** [comment]
Also running into this issue. Additional comments:

I'm attempting to grab `TeamData` from a match using the following on cassiopeia `5.0.1` installed via pip:

```
import cassiopeia as cass

cass.set_riot_api_key(KEY_HERE)

summoner = cass.get_summoner(name="FromIron", region="NA")

mh = cass.get_match_history(continent=summoner.region.continent, puuid=summoner.puuid)
mh[0].teams
```
I was expecting the output to be an array of size 2 containing TeamData like:

`[<cassiopeia.core.match.Team object at 0x1077193a0>, <cassiopeia.core.match.Team object at 0x107719130>]`

But instead I'm receiving an empty array:

`[]`

---

This might be caused by a lazy loading issue at: https://github.com/meraki-analytics/cassiopeia/blob/32c25b3cec5364e5b518816fcabff781cc751d85/cassiopeia/core/match.py#L2029-L2036

which might have to get loaded like this prior to access: https://github.com/meraki-analytics/cassiopeia/blob/32c25b3cec5364e5b518816fcabff781cc751d85/cassiopeia/core/match.py#L2012-L2017

**Comment by jjmaldonis** [comment]
This seems to be fixed. I saw that `...team.tower_kills` works.
