### ISSUE TITLE
keeps throwing 403 error while my api key works elsewhere 

### ISSUE THREAD

**Issue by riozzz** [meraki-analytics/cassiopeia#419]
I was using cass to fetch matchids from riot api, It went well during the first 2 days. Today, at some point, it started to throw 403 errors, at first, I thought my api key was blacklisted and therefore I had to register a personal app. Then, I tried another wrapper called riot watcher, and my api key works on it.
This upsets me cuz now I am collecting my data 10 times slower somehow. Any idea how this happened? (by the time I wrote this, it's still not working)

**Comment by riozzz** [comment]
follwing up this issue, I found out if i didn't call cass.apply_settings, it worked fine. So there was something wrong with the configuration maybe?

**Comment by jjmaldonis** [comment]
I don't know how you are setting your API key, but I'm guessing this is what's happening:
1. Somehow your API key is being set.
2. When you call `cass.apply_settings`, it is overwriting the set API key. This part is intentional.

You may need to re-set your API key after you call `cass.apply_settings`, or set your `RIOT_API_KEY` environment variable (which will by used by `cass.apply_settings`).
