### ISSUE TITLE
Get champions owned (summoner)

### ISSUE THREAD

**Issue by Braydenrudisill** [meraki-analytics/cassiopeia#420]
Hello! I've been working on a personal tool with a friend and it would be helpful to put all of our playable champions into a list. Would it be possible to implement a method for retrieving playable / owned champions for a specific summoner? Thanks.

**Comment by jjmaldonis** [comment]
Hello! Unfortunately this is not possible with the Riot API, but you can get this information from the LCU. You can find more info on the Riot API discord server. The reason this info is not available over the API is because people could use it to identify the value of an account, and then target that account for hacking/phishing if the account was considered to be "high value".
