### ISSUE TITLE
Need Help - Databasing issue..?  "500 error"

### ISSUE THREAD

**Issue by hijaek** [meraki-analytics/cassiopeia#53]
I guess this is more like a stupid question then a issue ticket... 
I'm just really new to this whole api and db thing. I just know that there is a call limit in riot api and that using db can resolve the issue. That is why I really appreciate your library.

But then... I do not really know how to take advantage of the db... 

What I am trying to do is extracting all my ranked match list of season5.
And for all ten participants of each match, I want to know the champ statistics of the champ selected by each participant. I'm making it into a data frame. So the table would look sth like below
[match#1, participant#1, dyrus, mundo, kda, gold]
...
[match#1, participant#10, doublelift, vayne, kda, gold]

Now..  apparently it's a quite heavy work (at least in the way I coded it). If I run my code for 10~20 matches it takes some time but still works the exact way I wanted. But if I run the code for more than about 30~50games it crashes and gives me 500 error.And when I went to developer.riotgames.com, I see messages like "Rate limit exceeded 83 times in the last 6 hours." I thought I shouldn't be seeing this message when I'm using db. 
Though I read that cass offers "automatic databasing", I was getting a feeling that I'm still missing sth silly to take advantage of this "databasing" concept.
I don't want to waste your time by asking to teach me technical things, but I was hoping if I could get some sort of guidance to fully utilize your library. Below is the code I used 

```
from cassiopeia import riotapi
from cassiopeia.core import *
from cassiopeia.dto import *
from cassiopeia.type import *
from cassiopeia.type.core.common import *
from cassiopeia.type.core.common import LoadPolicy
import random
import cassiopeia.riotapi
import cassiopeia.dto.statsapi
import cassiopeia.core.requests
import cassiopeia.type.core.common
import cassiopeia.type.core.stats
import time

import numpy as np
import pandas as pd
riotapi.set_rate_limit(3000, 10)
riotapi.set_load_policy(LoadPolicy.eager)
riotapi.set_load_policy(LoadPolicy.lazy)
key="abcd"
riotapi.set_region("NA")
riotapi.set_api_key(key)

def extract_participant(sum_name): 
    quetype=Queue.ranked_solo    
    myseason=Season.season_5 
    summoner = riotapi.get_summoner_by_name(sum_name)
    mygamelist=riotapi.get_match_list(summoner, num_matches=50, ranked_queues=quetype, seasons=myseason) #matchlist objects
    mydict= dict()

    for game in mygamelist:
        mydict[game.id]=[]
        for i in range(0,10):
            participant=game.match().participants[i] 
            champstat=participant.summoner.ranked_stats(season=myseason)[participant.champion]
            participant_list=[]
            participant_list.append(participant.summoner_name)
            participant_list.append(participant.side)
    return mydict

d = pd.Series(extract_participant('dyrus'))
```

**Comment by sbrodehl** [comment]
So every call you make to the API can be saved in a DB. If you later need the same information you gathered before you don't need the call the API again, instead you just look up the data in the local DB and save a call. Cass will buffer data using SQLAlchemy if you use cass from riotapi.

To fix your problem we'll take a look at your code...
Most important, the rate limit.
```python
riotapi.set_rate_limit(3000, 10)
```
As far as I remeber the default development limit is 
```
10 requests every 10 seconds
500 requests every 10 minutes
```
and that makes sense, because you run into problems with more matches you analyse. (I will fix the README...)
So this should be something like  this...
```python
riotapi.set_rate_limit(500, 10)
```
You can check your personal rate limit in your dev dashboard [here](https://developer.riotgames.com).
After this change you should be able to analyse any number of matches.

**Comment by hijaek** [comment]
Hm I changed to 
riotapi.set_rate_limits((10, 10), (500, 600))
But I still get  "assiopeia.type.api.exception.APIError: Server returned error 500 on call"

Also my dashboard says "Rate limit exceeded 96 times in the last 6 hours."
The graph also says that what i just ran def exceeds the limit during the time

**Comment by jjmaldonis** [comment]
@sbrodehl Thanks a million for helping us with these issues. We really appreciate it.

It's relatively normal to get 500s. I get them quite a bit, and retrying a couple times usually does the trick. It's just a temporary downtime in the Riot API that is unavoidable.

However, you definitely should not be exceeding the rate limits with those numbers. Did you double check your developer key limits? I can't believe they wouldn't be 10/10 and 500/600, but maybe yours are off for some reason (or maybe they reduced them due to too many 429s before?). 

>But if I run the code for more than about 30~50games it crashes and gives me 500 error.

Check out our `auto_retry` function (and how it's used (you can copy-paste)) in one of our examples:  https://github.com/meraki-analytics/cassiopeia/blob/master/example/match_collection.py  I use this all the time for projects like yours when I need to pull a bunch of data and I want to retry 500s a few times. Hopefully that will solve most of your issues. After a few hours I often get two 500s in a row that the program still quits, but that's just something you might have to deal with unless you want to really stress out Riot's servers (which we don't recommend).

I have no idea what's going on with your rate limit though, so be careful with that. We don't want you to get blacklisted. A few users have had similar problems, but they have decided it was their fault rather than Cass's. Hopefully it's just a number change, and it's clear when you turn on `print_calls` (see below). We'd be happy to help you figure it out though if you keep providing us with helpful. information.

>Though I read that cass offers "automatic databasing", I was getting a feeling that I'm still missing sth silly to take advantage of this "databasing" concept.

In order to use the databasing that Cass offers, you have to have some sort of database set up first, and then connect Cass to it. We desperately need some documentation on that, and we are going to try to write some in the next week or two. There a few options for types of databases that you can choose, and I don't know enough about them personally to recommend any. See here: http://docs.sqlalchemy.org/en/latest/core/engines.html   One thing you can also do is create an in-memory-only database, which will be destroyed when your program quits. If you want a persistent database, you will have to set one up on your computer first, then connect SQLAlchemy to it within your python program (see the constructor at https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/api/store.py#L203). Doing this will allow you to keep a record of all the data you have pulled. I don't know if I would recommend doing this right off the bat unless you are trying to pull thousands and thousands of games and use them multiple times. If you choose to go with the in-memory database (Ctrl+F "memory" here: http://docs.sqlalchemy.org/en/latest/core/engines.html), you will need to be careful that you do not pull so much data that your computers memory fills up, or your computer will crash. Essentially, if your memory will fill up then you will have to use a persistent database (i.e. one that saves the data permanently on your computer), but if you only need the data once and you don't need to keep it all in memory the entire time, then an in-memory cache should work.

Despite all that discussion about databasing, Cass still does some automatic caching on it's own. If you turn `riotapi.print_calls(True)` on, you will be able to see every call that Cass makes to Riot. If you run

    riotapi.get_champions()
    riotapi.get_champion_by_name("Annie")

you will see that on the first call, Cass gets the data from Riot. However, on the second call, Cass recognizes that it already has Annie, and pulls it from the cache. This is independent of any database you install. Also, you can use this `print_calls` function to help figure out what's going on with all your requests. (You should also see it pause every ~10 calls to wait for the rate limit quite often.)


>I'm just really new to this whole api and db thing. I just know that there is a call limit in riot api and that using db can resolve the issue. That is why I really appreciate your library.

Thanks! We are glad you like it and find it useful. It is written for exactly people like you (and us) who want to use the API but not deal with all the un-fun stuff. We just want to access the data and not have to worry about the intricacies of the API itself. That's what Cass is all about.

>But then... I do not really know how to take advantage of the db...

This is in part our fault due to lack of documentation. We know this really needs to be done, but we have been backlogged on a few other important projects recently. However, we plan to get much better documentation in the next week or two! In the mean time, hopefully what was posted above helps. If not, we'll keep trying to help out.
