### ISSUE TITLE
how to count API requests

### ISSUE THREAD

**Issue by hijaek** [meraki-analytics/cassiopeia#56]
I have a question about what accounts as a single "request" or "call" to API when I use Cassiopeia.
I'm trying to reduce as many api requests as possible here.

Let's say I have
```

match_one = matchobject
dyrus=match_one.participant[0]     ### the first participant of this match is dyrus
champstat=dyrus.summoner.ranked_stats(season=Season.season_5)[dyrus.champion]

```

"**dyrus**" is a participant object of a game. and the particiapnt is Dyrus
"**champstat**" gives me the Dyrus's season 5 ranked statistics of the champion he played for **match_one** 

Now I want to collect a few specific statistics of Dyrus's poppy into a list. So I say,

```
dyruslist=[]

dyruslist.append(dyrus.champion.id)

dyruslist.append(champstat.wins)
dyruslist.append(champstat.kda)
dyruslist.append(champstat.gold_earned)

```

My question here is  - _how many "api requests" have I just made?_

is it 4? because I asked for four different data?
(_dyrus.champion.id, champstat.wins, champstat.kda, champstat.gold_earned_)

or is it just 1? since everything really came from the summoner object, "**dyrus**"?

or sth else?

If it's 4, would you have any hints that might reduce the number of requests?

.
.
.
.
.

One idea was while keeping everything the same, I use "to_json" attribute for **champstat**.

match_one = matchobject
dyrus=match_one.participant[0] 
champstat=dyrus.summoner.ranked_stats(season=Season.season_5).**to_json**
champstat[champid][kda]

(_something like this_)

then **champstat** would be in json format and I use this jason to find out wins, kda, and gold earned. Since i'm just reading numbers from a single json, would this method reduce number of "requests"?

**Comment by hijaek** [comment]
btw, please let me know if this kind of question needs to be asked somewhere else. I'm not even sure if this is a question specific to Cassiopeia or more of a broader python/api question ...

**Comment by robrua** [comment]
Hey - to answer the title question directly, you can use [the get_requests_count](http://cassiopeia.readthedocs.org/en/latest/cassiopeia/riotapi.html#cassiopeia.riotapi.get_requests_count) method to keep track of how many API calls have been used in your cass code.

> My question here is - how many "api requests" have I just made?
It's hard to tell exactly, because Cass is always doing its level best to ensure that as few calls as possible are being used in the long run. In this particular case (only considering the lines of code in your post), you can't have used more than 2 API calls (plus a static-data call, but they don't count towards your rate limit).

If you're using the Lazy load policy, Cass will use an API call to retrieve the Summoner object for Dyrus when you first call `dyrus.summoner` (but will cache it and won't do it again next time). In some cases, it won't make any calls at all here.

Cass will also use an API call for the `ranked_stats(season=Season.season_5)` call to get those stats. This one **will not** be cached by Cass automatically, so be careful not to call this method in a tight loop.

None of the code in your second block will make any API calls, as you've already loaded all that data through the calls above.

> since everything really came from the summoner object, "dyrus"?
The Cass object hierarchy does not mirror the Riot API's exactly. Some of the methods you can call on a Summoner, Match, or similar object are convenience methods that will make another API call to get information that normally isn't contained in that object. An example of this is `summoner.ranked_stats()`. In the Riot API, ranked stats aren't contained in the Summoner object. Cassiopeia provides this as a shortcut to calling `riotapi.get_ranked_stats(summoner)`. In general, though not always, methods of Cass objects will make additional API calls, whereas attributes usually won't (unless that data will be cached after the first call).

> One idea was while keeping everything the same, I use "to_json" attribute for champstat.
This might be a useful exercise to help understand the differences between what is available with a Cass object and what is directly served by the Riot API, but this will **not** have an effect on the number of calls you'll have to make.

The entire point of Cass is to make dealing with the JSON that the Riot API sends easy and efficient. By outputting the JSON and getting data from that afterwards, you're defeating the purpose of using Cass in the first place.

A Cass object will _never_ make another API call to get you data that is already contained within that object's JSON. It only ever makes additional calls to get information that it doesn't already have.

> btw, please let me know if this kind of question needs to be asked somewhere else. I'm not even sure if this is a question specific to Cassiopeia or more of a broader python/api question ...

No worries, this is the correct place to ask. What you're asking is definitely within the scope of Cass, rather than Python/API. We also have a Slack group for people who are interested in a quicker feedback loop for Cass and other Meraki Analytics tools. Let me know if you'd like to be added to it.

To sum this all up: A lot of thought went into trying to ensure that Cass is always using as few API calls as possible. It may be valuable to read about the [load policies](http://cassiopeia.readthedocs.org/en/latest/loadpolicy.html#load-policies) in Cass if you're concerned about optimizing call usage. Each policy makes different assumptions about how you're using the data, but we're reasonably certain that each policy makes the best possible use of your rate limit given those assumptions.

**Comment by jjmaldonis** [comment]
Hopefully Rob cleared things up for you. In the code that you pasted, I think I found a spot where your thinking is different from what Cass is doing:

    match_one = matchobject
    dyrus=match_one.participant[0]     ### the first participant of this match is dyrus

This is all good and I think you understand what is going on.

    champstat=dyrus.summoner.ranked_stats(season=Season.season_5)[dyrus.champion]

On the above line, `dyrus` is a `Participant` in `match_one`. However, `dyrus.summoner` is THE `Summoner` Dyrus, not the participant in `match_one`. The summoner Dyrus participated in `match_one`, but he does not "belong" to it. `Participants` in a `Match` have stats like `gold`, but when you talk about Dyrus as a Summoner, he doesn't have "gold" -- he has a name, an ID, a number of Riot Points (which we can't see), a match history (that we can pull from the Riot API), etc. The `Summoner` Dyrus is different than the `Participant` Dyrus in `match_one`.

So when you do `dyrus.summoner.ranked_stats(...)`, you are *not* getting Dyrus's season 5 ranked statistics of the champion he played *for match_one*. You are getting Dyrus's season 5 ranked statistics for *every match he has played in season 5*.

**Comment by hijaek** [comment]
I use "Summoner" because I wanted to get the background information of Dyrus.
1) I pick up a participant of the "match_one" (who's dyrus here)
2) And I want Dyrus's past statistics of the champ he played for this "match_one"
    -if Dyrus played poppy in match_one, I want to know how dyrus did with poppy in season5.

_dyrus.summoner.ranked_stats(season=Season.season_5)_**[dyrus.champion]**

that's why i am moving to participant.summoner, instead of the participant object itself.

But it IS a long thread of objects and attributes. Do you think there is a better way to get what I want?

**Comment by jjmaldonis** [comment]
Ahh you are right, I didn't understand that correctly.

It's possible to save one API call if you use `baseriotapi` instead by not getting the dyrus's `Summoner`.

    from cassiopeia import baseriotapi
    match = baseriotapi.get_match(...)
    dyrus=match_one.participant[0]
    all_stats = baseriotapi.get_ranked_stats(dyrus.id, season=Season.season_5)


However, you will have to parse out the data for just `dyrus.champion` yourself. See [here](https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/core/statsapi.py#L23) for a few lines of code that might help.

**Comment by hijaek** [comment]
Thanks tons guys!
