### ISSUE TITLE
How to secure the API key?

### ISSUE THREAD

**Issue by jason2249** [meraki-analytics/cassiopeia#78]
Hi all,

Sorry if this is the wrong place to post this. I was looking at the documentation and it says to do riotapi.set_api_key("YOUR-API-KEY-HERE") to set the API key. However, the Riot documentation says for a production key, you need to "have the client application access your own server, which then makes the appropriate request to the API using HTTPS.". How would this be done with cassiopeia? I'm new to servers in general - would I need to use a server from say, AWS and have that call the set_api_key method? Thanks in advance for your help!

Best,
Jason

**Comment by jjmaldonis** [comment]
Hey Jason,

If you are not making a production app and just doing development for now,
you don't need a server yet. When you get to the point where you want to
make a website and ask Riot for a production key, you will need a server.

In either case, one of the best ways to secure your API key is to make
Cassiopeia/Python read it in through an environment variable. There are two
relevant links in Cassiopeia, one is from an example
<https://github.com/meraki-analytics/cassiopeia/blob/master/examples/calculate_average_kda.py#L19>
and one is from the setup documentation
<http://cassiopeia.readthedocs.io/en/latest/setup.html#setting-additional-environment-variables>
.

If you haven't dealt with environment variables before, it's worth googling
a bit about them.

Let us know if something doesn't make sense and we are happy to help out!

Best,
Jason

**Comment by robrua** [comment]
To expand on the process of securing the API key when you _are_ building a production app:

The most common way to do this is, as you mentioned, having the client code access an intermediate server to get information from the API while the server makes the actual requests to the API. This "hides" the API key behind the server and removes the need for the client code to know it.

**Cassiopeia is not currently designed for use in client code under this architecture**. I've heard from some users that they're using the type system Cass defines in client code without using the API request component, but there's currently no way to use Cass "in the normal way" in client code under this architecture. As a note, **this is one feature we're hoping to add in an upcoming™️ major release**.

That out of the way, it's probably worth mentioning that outside of games written entirely in python, it seems to be fairly rare that the client code for applications like this are written in python. Since most projects surrounding the Riot API tend to be websites, it's far more common for python to be used as the backend & server, with HTML/CSS/JS being used on the frontend & client code. If you're looking to go a similar route, we _do_ have an alpha-stage project to help bootstrap this type of setup. [kernel](https://github.com/meraki-analytics/kernel) is an extensible API proxy server, which will hide your key as well as handling (redis) caching & rate limiting for you. If you'd like to try using it, I'm happy to help you set it up & get working with it. Keep in mind, though, that some breaking changes are likely in that project's future.

Best,
Rob

**Comment by jason2249** [comment]
I basically have a Python script that I wanted to be able to distribute via PyPi. @jjmaldonis, for your environment variable suggestion, if I am understanding it correctly, would it only work for non-production projects? For example, if someone downloaded my project through PyPi, would they not be able to use the API key since it's stored in an environment variable on my computer? 

Also, since it currently isn't possible to use cassiopeia in this way, is there any guide you guys would recommend to get started with using a server? Would I just use something along the lines of these if I wanted to get started with a free server? http://www.ubuntufree.com/top-5-free-linux-web-hosting-that-are-reliable/

Best,
Jason

**Comment by ckcollab** [comment]
I haven't read everything here thoroughly, but in your production environment you should just have some environment variable set with your production API key. Much like how you probably have some env var api key for local dev.

When you want someone else to use your script, all they'll have to do is set some env var with their own API key.

I may be misunderstanding, apologies if so!

**Comment by robrua** [comment]
@jason2249 If you use the environment variable approach you will be able to distribute your code to other developers without compromising your API key. You'd just need to tell them what environment variable they need to set on their own machines that's getting pulled by your code.

If you're looking to distribute to non-developers, this approach doesn't really work as you can't have every random user needing to get an API key to use your application. In this case, you'll need a proxy server. If that's what you're after, let me know and I can expand on it & answer your above question about hosting services.

**Comment by jason2249** [comment]
@ckcollab That's also a really good idea! I was thinking of distributing to non developers, but I will definitely keep that in mind if I can't get the server thing working in time.

@robrua If you could expand on it, that would be awesome. If I am understanding this correctly, would I either use one of the above free linux servers, or sign up for AWS and launch an EC2 instance of a Linux VM, and then set up an apache HTTP server on it with a reverse proxy? Once that is done I would send http requests to my server instead of Riot's API, and the server would then send the request to Riot API. Does that sound about correct?

**Comment by robrua** [comment]
Yeah, that's accurate. We have a [different project](https://github.com/meraki-analytics/kernel) where we're trying to build a plug & play reverse proxy for the Riot API. In the process right now of getting a really good docker deployment of it.

As far as hosting services go, the 3 approaches I hear about most often are AWS, DigitalOcean, and Heroku.

AWS has a free tier where you can get an EC2 micro instance (1GB 1Ghz) for free for a year.

DigitalOcean also offers open-ended VMs that you can configure however you want. It's cheaper than AWS after the free year, but people seem to prefer AWS in general if cost isn't an object.

Heroku has a different model where they don't provision you a VM, you just upload your code/application and they handle all the infrastructure. They have a free tier as well.

**Comment by jason2249** [comment]
Ok, I'll give AWS a shot. Thanks for all your help!
