### ISSUE TITLE
So many service 429s

### ISSUE THREAD

**Issue by alyssa-adams** [meraki-analytics/cassiopeia#79]
Hello!

Background: Kinda-ish new to Python, and really new to rate limits/calls.

I'm running a code where I'm pulling all Master tier matches from 4 October. I'm using the code you've kindly provided "pull_masters_tier.py" as a base. To make sure things are running smoothly, I have the line "print("Got {0}".format(match))" to show me that it is gathering matches correctly. However, I'm getting a lot of "SERVICE 429." It looks something like this as the script is running:
Got Match #2310443223
SERVICE 429
SERVICE 429
Got Match #2310385404
Got Match #2310326909
Got Match #2310279651
Got Match #2310264967
Got Match #2310198579
Got Match #2310203223
Got Match #2309999296
SERVICE 429
SERVICE 429
Got Match #2309988823
Got Match #2309994894
Got Match #2309974510
SERVICE 429
SERVICE 429
SERVICE 429
SERVICE 429

Is this related to my rate limit? I don't want to get blacklisted and need to know if things are going alright. The data is getting saved to a file nicely, so that is alright. But I'm working on a very large project with this data and will need to gather data a LOT in the near future.

Sorry for the noob question and thank you in advance!

**Comment by alyssa-adams** [comment]
Oh no!!! When I try to request a large-ish amount at once (say, 100 summoners from the Masters tier), I get some really weird long error:

Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 92, in make_request
    content = limiter.call(execute_request, url, method, payload) if limiter else execute_request(url, method, payload)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/api/rates.py", line 158, in call
    return method(*args) if method else None
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 135, in execute_request
    response = urllib.request.urlopen(request)
  File "//anaconda/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "//anaconda/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "//anaconda/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "//anaconda/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "//anaconda/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "//anaconda/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pull_masters_tier.py", line 139, in <module>
    main()
  File "pull_masters_tier.py", line 57, in main
    for match in summoner.match_list(begin_time=gather_start):
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/core/common.py", line 107, in curried
    return self.method(obj, *args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/core/summoner.py", line 265, in match_list
    return cassiopeia.riotapi.get_match_list(self, num_matches, begin_index, begin_time, end_time, champions, ranked_queues, seasons)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/core/matchlistapi.py", line 52, in get_match_list
    history = cassiopeia.dto.matchlistapi.get_match_list(summoner.id, num_matches, begin_index, begin_time, end_time, champion_ids, ranked_queues, seasons)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/matchlistapi.py", line 40, in get_match_list
    return cassiopeia.type.dto.matchlist.MatchList(cassiopeia.dto.requests.get(request, params))
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 42, in get
    return make_request(request=request, method="GET", params=params, static=static, include_base=include_base, tournament=tournament)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 108, in make_request
    raise cassiopeia.type.api.exception.APIError("Server returned error {code} on call: {url}".format(code=e.code, url=url), e.code)
cassiopeia.type.api.exception.APIError: Server returned error 503 on call: https://na.api.pvp.net/api/lol/na/v2.2/matchlist/by-summoner/20426711?api_key=XXXXXXX&beginTime=1475539200000


HALP

**Comment by alyssa-adams** [comment]
I have no idea if this will be helpful or not, but here's my .py file:

```
import os
from datetime import datetime
import pandas as pd
from cassiopeia import riotapi
from cassiopeia.type.api.exception import APIError
from cassiopeia.type.core.common import LoadPolicy
from cassiopeia.type.api.store import SQLAlchemyDB


def main():
    # Setup riotapi
    riotapi.set_region("NA")
    riotapi.print_calls(False)
    os.environ["DEV_KEY"] = "XXXXXXXX"
    key = os.environ["DEV_KEY"]  # You can create an env var called "DEV_KEY" that holds your developer key. It will be loaded here.
    riotapi.set_api_key(key)
    riotapi.set_load_policy(LoadPolicy.eager)

    # Load and connect to your database. (Comment this code to use local memory. Don't forget to comment db.close() below too.)
    # db = SQLAlchemyDB("mysql+mysqlconnector", "databse_hostname", "database_name", "username", "password")
    # riotapi.set_data_store(db)

    # Gather master names
    master = [entry.summoner for entry in riotapi.get_master()]
    #mastertests = master[:100]
    print("Pulled Master tier. Got {0} summoners.".format(len(master)))

    #Make empty lists for match information
    matchid = []
    versionpatch = []
    matchdate = []
    maptype = []
    queue = []

    p_names = []
    p_sides = []
    p_champs = []
    p_lanes = []
    p_roles = []
    p_golds = []
    p_wins= []

    #Define a start date, and then for each player in the master list, get the match ID number
    gather_start = datetime(2016, 10, 4)  # 1 day after patch 5.14, year month date
    for summoner in master:
        for match in summoner.match_list(begin_time=gather_start):
            # If you are connected to a database, the match will automatically be stored in it without you having to do anything.
            # Simply pull the match, and it's in your database for whenever you need it again!
            # If you pull a match twice, the second time it will be loaded from the database rather than pulled from Riot
            # and therefore will not count against your rate limit. This is true of all datatypes, not just Match.
            match = get_match(match)
            print("Got {0}".format(match))

            #Then save the match information to some empty lists
            matchid.append(match.id)
            versionpatch.append(match.version)
            matchdate.append(match.creation)
            maptype.append(match.map)
            queue.append(match.queue)

            #Now make empty lists for the player information
            p1name = []
            p1side = []
            p1champ = []
            p1lane = []
            p1role = []
            p1gold = []
            p1win = []

            #Make a loop to get the rest of the participants
            for part in match.participants:
                p1name.append(part.summoner_name)
                p1side.append(part.side)
                p1champ.append(part.champion.name)
                p1lane.append(part.timeline.lane)
                p1role.append(part.timeline.role)
                p1gold.append(part.stats.gold_earned)
                p1win.append(part.stats.win)

            #Save information into the lists
            p_names.append(p1name)
            p_sides.append(p1side)
            p_champs.append(p1champ)
            p_lanes.append(p1lane)
            p_roles.append(p1role)
            p_golds.append(p1gold)
            p_wins.append(p1win)

    #db.close()

    filename = "master_data_4oct2016.csv"
    columns = ['matchid', 'versionpatch', 'matchdate', 'maptype', 'queue', 'p_names', 'p_sides', 'p_champs', 'p_lanes', 'p_roles', 'p_golds', 'p_wins']
    df = pd.DataFrame([matchid, versionpatch, matchdate, maptype, queue, p_names, p_sides, p_champs, p_lanes, p_roles, p_golds, p_wins], index = columns)

    df = df.T
    df.to_csv(filename)

    #print(df)


def get_match(reference):
    """ Try to pull the referenced match from Riot's servers. If we can an error that
        we should retry, we will. If it fails a second time, we just skip it.
    """
    try:
        return riotapi.get_match(reference)
    except APIError as error:
        # Try Again Once
        if error.error_code in [500]:
            try:
                return riotapi.get_match(reference)
            except APIError as another_error:
                if another_error.error_code in [500, 400, 404]:
                    pass
                else:
                    raise another_error

        # Skip
        elif error.error_code in [400, 404]:
            pass

        # Fatal
        else:
            raise error


if __name__ == "__main__":
    main()

```

**Comment by sbrodehl** [comment]
429 is related to rate limiting, see https://developer.riotgames.com/docs/rate-limiting
Cass will take of this and wont make any calls in the next seconds, maybe you noticed this.

503 means that the server is overloaded or down, nothing we can do here.

**Comment by robrua** [comment]
Hey, the SERVICE 429 messages you're seeing aren't indicative of you doing anything wrong; The API has a few different types of 429 errors, as detailed in the link from @sbrodehl's comment. In theory, Cass should be internally handling each different type of 429 properly and you shouldn't get blacklisted using it.

You'll get a SERVICE 429 from Cass any time that either the API infrastructure is being throttled because of heavy load, or the underlying service that provides the API endpoint is overloaded. In both cases, these errors won't count towards your "rate limit exceeds" for blacklisting. The service underlying the match endpoint in particular has been overloaded a lot recently, so seeing these errors gathering matches is to be expected right now.

If you see a USER 429, *those* count towards your "rate limit exceeds". If you're seeing them often you'll want to shut down your match gathering and report it to us. We try to make sure that Cass will handle your rate limit properly and you won't get blacklisted using it, but there's unfortunately been times when a bug in Cass is causing more USER 429s than are acceptable.

You can check how many times your rate limit has been exceeded recently on your dashboard at https://developer.riotgames.com/. A few of these USER 429s are to be expected, since the Cass rate limiter can't sync perfectly with the rate limiting on Riot's end. If you're seeing larger numbers of "rate limit exceeds" on your dashboard please let us know so we can track down the rate limiting bug.

On a side note, those SERVICE 429 messages aren't supposed to be shown in the release version, and I guess we accidentally left some debug code in the release. Whoops!

As far as your 503 Error goes, it means the service is temporarily down on Riot's end. As @sbrodehl mentioned, there's not really anything you can do about that as a user other than wait for it to be back up. Cass raises an error when this happens so that you can use a try/except block to handle it however you see fit. The approach will change based on your preferences/requirements, but for a match gathering script I recommend either waiting for a relatively long time (5mins or so) then retrying the same call, or just saving your current progress to disk or you database and terminating the script to be re-run later.

LMK if that covers it or if there's anything else I can help with.

**Comment by alyssa-adams** [comment]
Thank you both so much! You're very helpful!
Good to know things are actually going as they are supposed to. It makes a lot of sense that I'm getting all these SERVICE 429 errors if I'm trying to get so much data at once. I'll keep fiddling with it, but so far there isn't any worries on my API page about being blacklisted, so good to go! I'll just pick up the data where I can to work around the 503 errors.
Thanks again! :D

**Comment by sbrodehl** [comment]
You can also register for a production API key with much higher rate limits, if you show Riot a working app.
And you can query endpoints, e.g. NA and EUW, simultaneously. That helps if you need data from different regions.

**Comment by alyssa-adams** [comment]
@sbrodehl, I would really love to get a production API key! However, since I'm doing this for a PhD project, I don't actually have an app I can register. But I might be interpreting what an "app" is incorrectly. When I think of "app", I think of gg.op things. However, I've noticed that a lot of times in website development, having an "app" really just means getting an API key and using it, not really developing a full-blown java-based applications complete with a nice GUI and fun buttons for user to use. So like...... what's an app here?

**Comment by jjmaldonis** [comment]
@alyssa-adams I believe you technically have to have something that other people can view or use in order to get a production key, but I would definitely submit a user note to Riot to ask them. If you layout a somewhat detailed project structure for a PhD project, they may make an exception.

That said, the very first production key I got was for an _extremely_ basic website, so you may be able to spin one up quickly and talk about your PhD project on it, and maybe have some preliminary results with a small dataset. Your funding agency will also love that, so you/your advisor might get major brownie points for the whole Broader Impacts stuff.

So if you can either give them a project outline if you already have one, or if you or a friend can spin up a basic website (maybe even a wordpress site if you are just going to paste in some preliminary results) then I'd guess that you have a good shot at getting a production key.

**Comment by alyssa-adams** [comment]
I really love the idea of starting up a basic website! Thanks for that! I will actually start one up now, since I'll be able to put up some preliminary data. My advisor will certainly be happy about it too!

**Comment by robrua** [comment]
Feel free to email us or add more issues if you have other questions or run into additional problems
