### ISSUE TITLE
TypeError: list indices must be integers or slices, not Summoner / Str

### ISSUE THREAD

**Issue by fculpo** [meraki-analytics/cassiopeia#86]
Getting these errors when running parse_match_information.py example

```
File "E:/Workspace/cassiopeia/examples/parse_match_information.py", line 39, in main
    champion = match.participants[dyrus].champion
TypeError: list indices must be integers or slices, not Summoner

File "E:/Workspace/cassiopeia/examples/parse_match_information.py", line 39, in main
    champion = match.participants["Dyrus"].champion
TypeError: list indices must be integers or slices, not str
```

**Comment by jjmaldonis** [comment]
Ah, we temporarily removed that functionality. You can just ignore those problematic lines for now.

**Comment by fculpo** [comment]
Do you plan to reenable it in a near future ?
it seems quite useful :)

**Comment by jjmaldonis** [comment]
Definitely. We are working on a major rework of Cass and have it in that version. However, in this version we only implemented it on one or two things, and it was kinda hacked together, so we removed it because we are worried about bug reports and such. We didn't think many people were using it yet... But when we get the new version out, it will have that and a whole bunch of other fun stuff!

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
