### ISSUE TITLE
Error when connecting python to mysql

### ISSUE THREAD

**Issue by istiak** [meraki-analytics/cassiopeia#94]
Right now I'm just trying to store a summoner into my mysql database.  I get the error: 

ArgumentError: 
Could not parse rfc1738 URL from string 
'mysql-connector-python://root:password@localhost/Cass'

Here is the relevant code : 

    **# Load and connect to your database. (Comment this code to use local memory. Don't forget to comment db.close() below too.)
    db = SQLAlchemyDB("mysql-connector-python", "localhost", "Cass", "root", "password")
    riotapi.set_data_store(db)

    summoner = riotapi.get_summoner_by_name("Shiptur") 
    print("Stored {thisSum} in my database".format(thisSum=summoner))

    db.close()**

Here is additional imports:
````
import os
import pymysql
from datetime import datetime

from cassiopeia import riotapi
from cassiopeia.type.api.exception import APIError
from cassiopeia.type.core.common import LoadPolicy
from cassiopeia.type.api.store import SQLAlchemyDB
````

Thanks for the help!

**Comment by jjmaldonis** [comment]
Woofa, I'm not sure about this one off the top of my head.

My initial reaction after some googling is that you may try changing `mysql-connector-python` to `mysql+mysql-connector-python`. Reading this page might help: http://docs.sqlalchemy.org/en/latest/core/engines.html

**Comment by istiak** [comment]
Alright with your help I was able to mess around with it and now I have a new error on data integrity. Yay progress!  Here's the whole error: 

`IntegrityError: (pymysql.err.IntegrityError) (1215, 'Cannot add foreign key constraint') [SQL: '\nCREATE TABLE `MatchParticipant` (\n\t`championId` INTEGER, \n\t`highestAchievedSeasonTier` VARCHAR(30), \n\t`participantId` INTEGER, \n\t`spell1Id` INTEGER, \n\t`spell2Id` INTEGER, \n\t`teamId` INTEGER, \n\t_id INTEGER NOT NULL AUTO_INCREMENT, \n\t_match_id INTEGER, \n\tPRIMARY KEY (_id), \n\tFOREIGN KEY(_match_id) REFERENCES `MatchDetail` (`matchId`) ON DELETE CASCADE\n)\n\n']`

The only change I made to the code is here: 

 ```
db = SQLAlchemyDB("mysql+pymysql", "localhost", "Cass", "root", "password")
    riotapi.set_data_store(db)
```

**Comment by jjmaldonis** [comment]
Unfortunately I have never used pymysql, and it looks like that error is a result of pymysql and our implementation of sqlalchemy. It's likely that somewhere in that table we are not properly defining the foreign keys. Unfortunately I know very little about this and I'm not likely to figure anything new out anytime soon.

You could try a few things: 1) simplify things as much as possible in order to get the minimal amount of code that reproduces the error. 2) post a question on a forum, such as stack overflow, the pymysql forums/mailing list, etc.

Sorry I can't be of more help.

**Comment by jjmaldonis** [comment]
After talking to AmirKat on the discord, I believe I know what the issue is. My guess is that somewhere the data is getting jsonified twice, so the already-jsoned-str is getting passed through `json.dumps`.

I don't know where the would be occurring, and it might take some time to track down.

@robrua

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
