### ISSUE TITLE
403 error, possibly blacklisted

### ISSUE THREAD

**Issue by TheK272** [meraki-analytics/cassiopeia#98]
So the function of my program is to collect a large amount of game data to do predictive modeling based on. I have been running/debugging/changing it for the past week or so and have had no issues. Yesterday I was able to run it for 2-3 hours without it stopping and gathered data from around 2500 games. I tried to run it today and after 20 minutes or so I got a 403 error. I then went to the Riot API reference page and got another 403 there. However it is now working again and I am not getting any 403's, so I'm not sure if I was actually blacklisted.

**Comment by sbrodehl** [comment]
Have you checked your status at [developer.riotgames.com](https://developer.riotgames.com)?
You can check your API key usage of the last 7 days.

**Comment by TheK272** [comment]
These are my number of requests in the past 24 hours:

API METHOD	# OF REQUESTS
matchlist-v2.2.getMatchList	18,716
match-v2.2.getMatchById	17,883
summoner-v1.4.getBySummonerIds	17,756

Last Seven Days: 

API METHOD	# OF REQUESTS
matchlist-v2.2.getMatchList	24,599
match-v2.2.getMatchById	23,655
summoner-v1.4.getBySummonerIds	23,443

Looking at 30 minute intervals it looks like I have gotten as high as 1500 in 30 minutes which is the max I can call. And for some reason I'm not getting the 403 anymore so I guess I'm all good.

**Comment by jjmaldonis** [comment]
There have been all sorta of random outages with the API over the last week, so it may have something to do with that.

However, Cass currently doesn't implement rate limiting for individual endpoints, which _could_ get you blacklisted. However, that should be completely impossible if you are gather data using a dev key. The next version of Cass will have the fully implemented new rate limits, but that likely won't be available for a while still (partly because those rate limits will only come into effect very rarely, and only for "power users" who have full blow apps with a production key).

If you had gotten blacklisted, I don't think they re-enable you after a period of time. I think in order to get re-enabled, you need to explain to them how you have fixed the problem. So my guess is that the 403s were an issue on Riot's end.

If you'd like, you can close this issue -- and you can always re-open it if you find out there is a problem. Thanks!

**Comment by jjmaldonis** [comment]
Yup, looks like this was an issue on Riot's end. There are a bunch of people getting 403s now due to the match endpoint being down. I'm going to close this issue so it doesn't confuse other people who look at the issues, and so they don't worry about getting blacklisted if they use Cass.
